### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by robfranceschi** [edward1997104/make-a-shape#1]
Hi @edward1997104,
thanks for the interesting paper!
I was wondering if the code and pretrained models will be made public.
If so, do you have a rough estimate on the date?
Many thankss

**Comment by jloveric** [comment]
Interested in availability as well

**Comment by hiyyg** [comment]
:+1:

**Comment by edward1997104** [comment]
Thank you very much for your interest! I am not sure of the exact release plan for the code/pre-trained model, as I am no longer able to access them. If there are any updates on the release, I will try to keep you posted.

**Comment by edward1997104** [comment]
Thank you for the waiting. The pre-trained models are released at: https://github.com/AutodeskAILab/Make-a-Shape.
